### ISSUE TITLE
Tried to use aps-ema-extractor but got error

### ISSUE THREAD

**Issue by ksteinb** [rukmalf/aps-ema-extractor#1]
Hi,

i tried to use your application to read out the data from EMA for my PV installation, but i got this error:

klaus@gar-ws-rbg08:~/Downloads/aps-ema-extractor-master$ node aps-ema-extractor
LogLevel set to LOG_LEVEL_VERBOSE from config.
ERROR: Error: SyntaxError: Unexpected token u in JSON at position 0

First off:  LOG_LEVEL_VERBOSE seems to not work for some reason, after i commented out the test inside logVerbose, I got more details.

The problem was that I had some special characters in the password, they probably didn't get quoted in the authentication request.

After changing to a password without special characters, I could retrieve the data.

Btw: did you have more hints about the use of this application?

Sincerly,
Klaus

**Comment by rukmalf** [comment]
Hi Klaus! Many thanks for using this and for the feedback, and my apologies for taking so long to respond. I've expanded the README file, so hopefully it gives a bit more insight now how to use it. I still have to expand on the IFTTT setup too. I'll try and look into the encoding of the password first of all, and also on the discrepancy in log level behaviour secondarily. Let's keep this open till then.

**Comment by rukmalf** [comment]
Hi again Klaus! I've not really been able to keep up with this recently, and I realize that the API seems to no longer work. My real use was to get daily summaries by connecting to IFTTT so that I knew the system was online and operating, can't really think of other usages :) I'm going to close this issue and update the markdown to indicate the API issue as fixing log level probably won't make a difference at all. The new API is harder to understand than the old, but I'll post an update if I figure it out. Best regards! --Rukmal
